name: Build
run-name: ${{ github.event.head_commit.message }}
on:
  push:
    branches: [ "master", "dev" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      LAB_EX_REFERENCES: "/home/runner/work/dependencies"
      SL_REFERENCES: "/home/runner/work/dependencies"

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Download Dependencies
      run: wget https://github.com/marchellc/LabExtended/raw/refs/heads/refs/refs.rar
    - name: Install RAR
      run: sudo apt install -y rar
    - name: Move RAR
      run: cp refs.rar /home/runner/work/
    - name: Delete RAR
      run: rm refs.rar
    - name: Extract dependencies
      run: cd /home/runner/work/ && rar x refs.rar
    - name: CD back
      run: cd /home/runner/work/LabExtended
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --property WarningLevel=0
    - name: Create artifacts
      run: mkdir /home/runner/work/artifacts/ && cp ./LabExtended/bin/Release/net48/LabExtended.dll /home/runner/work/artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.3.4
      with:
        name: labextended
        path: /home/runner/work/artifacts/LabExtended.dll
        overwrite: true
